#txt_Opener

#Generated Form Function
function GenerateForm
{
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
    # Generated On: 05.10.2021 08:34
    # Generated By: Martin
    ########################################################################

    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    #endregion

    #region Generated Form Objects
    $form_Start = New-Object System.Windows.Forms.Form
    $school_add_btn = New-Object System.Windows.Forms.Button
    $work_add_btn = New-Object System.Windows.Forms.Button
    $checkedListBox2 = New-Object System.Windows.Forms.CheckedListBox
    $checkedListBox1 = New-Object System.Windows.Forms.CheckedListBox
    $school_opn_btn = New-Object System.Windows.Forms.Button
    $work_opn_btn = New-Object System.Windows.Forms.Button
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects

    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    #Provide Custom Code for events specified in PrimalForms.
    $school_opn_btn_OnClick =
    {
        $programme = $checkedListBox2.CheckedItems
        foreach ($programm in $programme)
        {
            start $programm
        }

    }

    $work_opn_btn_OnClick =
    {
        $programme = $checkedListBox1.CheckedItems
        foreach ($programm in $programme)
        {
            start $programm
        }
    }

    $work_add_btn_OnClick =
    {
        #TODO: Place custom script here

        #Generated Form Function
        function GenerateForm
        {
            ########################################################################
            # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
            # Generated On: 28.09.2021 15:32
            # Generated By: Martin
            ########################################################################

            #region Import the Assemblies
            [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
            [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
            #endregion

            #region Generated Form Objects
            $form_Add_Work = New-Object System.Windows.Forms.Form
            $path_label = New-Object System.Windows.Forms.TextBox
            $text_label = New-Object System.Windows.Forms.Label
            $search_btn = New-Object System.Windows.Forms.Button
            $add_btn = New-Object System.Windows.Forms.Button
            $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
            #endregion Generated Form Objects

            #----------------------------------------------
            #Generated Event Script Blocks
            #----------------------------------------------
            #Provide Custom Code for events specified in PrimalForms.
            $handler_label2_Click =
            {
                #TODO: Place custom script here

            }

            $search_btn_OnClick =
            {
                $searchfile = New-Object System.Windows.Forms.OpenFileDialog
                $searchfile.Filter = "ProgrammDatien |*exe;*.lnk";
                $searchfile.ShowDialog()
                $script:file = $searchfile.FileName
                $path_label.Text = "$file"

            }

            $handler_Mit_Click =
            {
                #$checkedListBox1.Items.AddRange([io.path]::GetFileNameWithoutExtension("$file"))
                $checkedListBox1.Items.AddRange($file)
                $form_Add_Work.Close()

            }

            $OnLoadForm_StateCorrection =
            {
                #Correct the initial state of the form to prevent the .Net maximized form issue
                $form_Add_Work.WindowState = $InitialFormWindowState
            }

            #----------------------------------------------
            #region Generated Form Code
            $System_Drawing_Size = New-Object System.Drawing.Size
            $System_Drawing_Size.Height = 355
            $System_Drawing_Size.Width = 380
            $form_Add_Work.ClientSize = $System_Drawing_Size
            $form_Add_Work.DataBindings.DefaultDataSourceUpdateMode = 0
            $form_Add_Work.Name = "form_Add_Work"
            $form_Add_Work.Text = "Arbeitsprogramme hinzufügen"

            $path_label.DataBindings.DefaultDataSourceUpdateMode = 0
            $System_Drawing_Point = New-Object System.Drawing.Point
            $System_Drawing_Point.X = 67
            $System_Drawing_Point.Y = 100
            $path_label.Location = $System_Drawing_Point
            $path_label.Name = "path_label"
            $System_Drawing_Size = New-Object System.Drawing.Size
            $System_Drawing_Size.Height = 20
            $System_Drawing_Size.Width = 192
            $path_label.Size = $System_Drawing_Size
            $path_label.TabIndex = 3

            $form_Add_Work.Controls.Add($path_label)

            $text_label.DataBindings.DefaultDataSourceUpdateMode = 0

            $System_Drawing_Point = New-Object System.Drawing.Point
            $System_Drawing_Point.X = 1
            $System_Drawing_Point.Y = 97
            $text_label.Location = $System_Drawing_Point
            $text_label.Name = "text_label"
            $System_Drawing_Size = New-Object System.Drawing.Size
            $System_Drawing_Size.Height = 23
            $System_Drawing_Size.Width = 100
            $text_label.Size = $System_Drawing_Size
            $text_label.TabIndex = 2
            $text_label.Text = "Dateipfad:"
            $text_label.add_Click($handler_label2_Click)

            $form_Add_Work.Controls.Add($text_label)


            $search_btn.DataBindings.DefaultDataSourceUpdateMode = 0

            $System_Drawing_Point = New-Object System.Drawing.Point
            $System_Drawing_Point.X = 265
            $System_Drawing_Point.Y = 98
            $search_btn.Location = $System_Drawing_Point
            $search_btn.Name = "search_btn"
            $System_Drawing_Size = New-Object System.Drawing.Size
            $System_Drawing_Size.Height = 23
            $System_Drawing_Size.Width = 86
            $search_btn.Size = $System_Drawing_Size
            $search_btn.TabIndex = 1
            $search_btn.Text = "Durchsuchen"
            $search_btn.UseVisualStyleBackColor = $True
            $search_btn.add_Click($search_btn_OnClick)

            $form_Add_Work.Controls.Add($search_btn)


            $add_btn.DataBindings.DefaultDataSourceUpdateMode = 0

            $System_Drawing_Point = New-Object System.Drawing.Point
            $System_Drawing_Point.X = 184
            $System_Drawing_Point.Y = 309
            $add_btn.Location = $System_Drawing_Point
            $add_btn.Name = "add_btn"
            $System_Drawing_Size = New-Object System.Drawing.Size
            $System_Drawing_Size.Height = 23
            $System_Drawing_Size.Width = 167
            $add_btn.Size = $System_Drawing_Size
            $add_btn.TabIndex = 0
            $add_btn.Text = "Programm hinzufügen"
            $add_btn.UseVisualStyleBackColor = $True
            $add_btn.add_Click($handler_Mit_Click)

            $form_Add_Work.Controls.Add($add_btn)

            #endregion Generated Form Code

            #Save the initial state of the form
            $InitialFormWindowState = $form_Add_Work.WindowState
            #Init the OnLoad event to correct the initial state of the form
            $form_Add_Work.add_Load($OnLoadForm_StateCorrection)
            #Show the Form
            $form_Add_Work.ShowDialog()| Out-Null


        } #End Function

        #Call the Function
        GenerateForm

    }

    $school_add_btn_OnClick =
    {
        #TODO: Place custom script here
        #Generated Form Function
        function GenerateForm
        {
            ########################################################################
            # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
            # Generated On: 28.09.2021 15:32
            # Generated By: Martin
            ########################################################################

            #region Import the Assemblies
            [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
            [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
            #endregion

            #region Generated Form Objects
            $form_Add_School = New-Object System.Windows.Forms.Form
            $path_label = New-Object System.Windows.Forms.TextBox
            $text_label = New-Object System.Windows.Forms.Label
            $search_btn = New-Object System.Windows.Forms.Button
            $add_btn = New-Object System.Windows.Forms.Button
            $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
            #endregion Generated Form Objects

            #----------------------------------------------
            #Generated Event Script Blocks
            #----------------------------------------------
            #Provide Custom Code for events specified in PrimalForms.
            $handler_label2_Click =
            {
                #TODO: Place custom script here

            }

            $search_btn_OnClick =
            {
                $searchfile = New-Object System.Windows.Forms.OpenFileDialog
                $searchfile.Filter = "ProgrammDatien |*exe;*.lnk";
                $searchfile.ShowDialog()
                $script:file = $searchfile.FileName
                $path_label.Text = "$file"

            }

            $handler_Mit_Click =
            {
                #$checkedListBox2.Items.AddRange([io.path]::GetFileNameWithoutExtension("$file"))
                $checkedListBox2.Items.AddRange($file)
                $form_Add_School.Close()

            }

            $OnLoadForm_StateCorrection =
            {
                #Correct the initial state of the form to prevent the .Net maximized form issue
                $form_Add_School.WindowState = $InitialFormWindowState
            }

            #----------------------------------------------
            #region Generated Form Code
            $System_Drawing_Size = New-Object System.Drawing.Size
            $System_Drawing_Size.Height = 355
            $System_Drawing_Size.Width = 380
            $form_Add_School.ClientSize = $System_Drawing_Size
            $form_Add_School.DataBindings.DefaultDataSourceUpdateMode = 0
            $form_Add_School.Name = "form_Add_School"
            $form_Add_School.Text = "Schulprogramme hinzufügen"

            $path_label.DataBindings.DefaultDataSourceUpdateMode = 0
            $System_Drawing_Point = New-Object System.Drawing.Point
            $System_Drawing_Point.X = 67
            $System_Drawing_Point.Y = 100
            $path_label.Location = $System_Drawing_Point
            $path_label.Name = "path_label"
            $System_Drawing_Size = New-Object System.Drawing.Size
            $System_Drawing_Size.Height = 20
            $System_Drawing_Size.Width = 192
            $path_label.Size = $System_Drawing_Size
            $path_label.TabIndex = 3

            $form_Add_School.Controls.Add($path_label)

            $text_label.DataBindings.DefaultDataSourceUpdateMode = 0

            $System_Drawing_Point = New-Object System.Drawing.Point
            $System_Drawing_Point.X = 1
            $System_Drawing_Point.Y = 97
            $text_label.Location = $System_Drawing_Point
            $text_label.Name = "text_label"
            $System_Drawing_Size = New-Object System.Drawing.Size
            $System_Drawing_Size.Height = 23
            $System_Drawing_Size.Width = 100
            $text_label.Size = $System_Drawing_Size
            $text_label.TabIndex = 2
            $text_label.Text = "Dateipfad:"
            $text_label.add_Click($handler_label2_Click)

            $form_Add_School.Controls.Add($text_label)


            $search_btn.DataBindings.DefaultDataSourceUpdateMode = 0

            $System_Drawing_Point = New-Object System.Drawing.Point
            $System_Drawing_Point.X = 265
            $System_Drawing_Point.Y = 98
            $search_btn.Location = $System_Drawing_Point
            $search_btn.Name = "search_btn"
            $System_Drawing_Size = New-Object System.Drawing.Size
            $System_Drawing_Size.Height = 23
            $System_Drawing_Size.Width = 86
            $search_btn.Size = $System_Drawing_Size
            $search_btn.TabIndex = 1
            $search_btn.Text = "Durchsuchen"
            $search_btn.UseVisualStyleBackColor = $True
            $search_btn.add_Click($search_btn_OnClick)

            $form_Add_School.Controls.Add($search_btn)


            $add_btn.DataBindings.DefaultDataSourceUpdateMode = 0

            $System_Drawing_Point = New-Object System.Drawing.Point
            $System_Drawing_Point.X = 184
            $System_Drawing_Point.Y = 309
            $add_btn.Location = $System_Drawing_Point
            $add_btn.Name = "add_btn"
            $System_Drawing_Size = New-Object System.Drawing.Size
            $System_Drawing_Size.Height = 23
            $System_Drawing_Size.Width = 167
            $add_btn.Size = $System_Drawing_Size
            $add_btn.TabIndex = 0
            $add_btn.Text = "Programm hinzufügen"
            $add_btn.UseVisualStyleBackColor = $True
            $add_btn.add_Click($handler_Mit_Click)

            $form_Add_School.Controls.Add($add_btn)

            #endregion Generated Form Code

            #Save the initial state of the form
            $InitialFormWindowState = $form_Add_School.WindowState
            #Init the OnLoad event to correct the initial state of the form
            $form_Add_School.add_Load($OnLoadForm_StateCorrection)
            #Show the Form
            $form_Add_School.ShowDialog()| Out-Null

        } #End Function

        #Call the Function
        GenerateForm


    }

    $OnLoadForm_StateCorrection =
    {
        #Correct the initial state of the form to prevent the .Net maximized form issue
        $form_Start.WindowState = $InitialFormWindowState
    }

    #----------------------------------------------
    #region Generated Form Code
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 439
    $System_Drawing_Size.Width = 775
    $form_Start.ClientSize = $System_Drawing_Size
    $form_Start.DataBindings.DefaultDataSourceUpdateMode = 0
    $form_Start.Name = "form_Start"
    $form_Start.Text = "Programm öffner"


    $school_add_btn.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 444
    $System_Drawing_Point.Y = 306
    $school_add_btn.Location = $System_Drawing_Point
    $school_add_btn.Name = "school_add_btn"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 300
    $school_add_btn.Size = $System_Drawing_Size
    $school_add_btn.TabIndex = 5
    $school_add_btn.Text = "Programme hinzufügen"
    $school_add_btn.UseVisualStyleBackColor = $True
    $school_add_btn.add_Click($school_add_btn_OnClick)

    $form_Start.Controls.Add($school_add_btn)


    $work_add_btn.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 31
    $System_Drawing_Point.Y = 307
    $work_add_btn.Location = $System_Drawing_Point
    $work_add_btn.Name = "work_add_btn"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 300
    $work_add_btn.Size = $System_Drawing_Size
    $work_add_btn.TabIndex = 4
    $work_add_btn.Text = "Programme hinzufügen"
    $work_add_btn.UseVisualStyleBackColor = $True
    $work_add_btn.add_Click($work_add_btn_OnClick)

    $form_Start.Controls.Add($work_add_btn)

    $checkedListBox2.DataBindings.DefaultDataSourceUpdateMode = 0
    $checkedListBox2.FormattingEnabled = $True
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 444
    $System_Drawing_Point.Y = 91
    $checkedListBox2.Location = $System_Drawing_Point
    $checkedListBox2.Name = "checkedListBox2"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 169
    $System_Drawing_Size.Width = 300
    $checkedListBox2.Size = $System_Drawing_Size
    $checkedListBox2.TabIndex = 3

    $form_Start.Controls.Add($checkedListBox2)

    $checkedListBox1.DataBindings.DefaultDataSourceUpdateMode = 0
    $checkedListBox1.FormattingEnabled = $True
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 31
    $System_Drawing_Point.Y = 91
    $checkedListBox1.Location = $System_Drawing_Point
    $checkedListBox1.Name = "checkedListBox1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 169
    $System_Drawing_Size.Width = 300
    $checkedListBox1.Size = $System_Drawing_Size
    $checkedListBox1.TabIndex = 2

    $form_Start.Controls.Add($checkedListBox1)


    $school_opn_btn.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 444
    $System_Drawing_Point.Y = 36
    $school_opn_btn.Location = $System_Drawing_Point
    $school_opn_btn.Name = "school_opn_btn"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 300
    $school_opn_btn.Size = $System_Drawing_Size
    $school_opn_btn.TabIndex = 1
    $school_opn_btn.Text = "Schulprogramme öffnen"
    $school_opn_btn.UseVisualStyleBackColor = $True
    $school_opn_btn.add_Click($school_opn_btn_OnClick)

    $form_Start.Controls.Add($school_opn_btn)


    $work_opn_btn.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 31
    $System_Drawing_Point.Y = 36
    $work_opn_btn.Location = $System_Drawing_Point
    $work_opn_btn.Name = "work_opn_btn"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 300
    $work_opn_btn.Size = $System_Drawing_Size
    $work_opn_btn.TabIndex = 0
    $work_opn_btn.Text = "Arbeitsprogramme öffnen"
    $work_opn_btn.UseVisualStyleBackColor = $True
    $work_opn_btn.add_Click($work_opn_btn_OnClick)

    $form_Start.Controls.Add($work_opn_btn)

    #endregion Generated Form Code

    #Save the initial state of the form
    $InitialFormWindowState = $form_Start.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $form_Start.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $form_Start.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
